POST https://mighty-savannah-23892.herokuapp.com/api/persons
Content-Type: application/json

{
  "name": "Heroku Person",
  "number": "050 123 4567"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "John Smith",
  "number": "044 654 3210"
}
